spring:
  application:
    name: gateway
  freemarker:
    enabled: true # Use Eureka dashboard FreeMarker templates
  cloud:
    gateway:
      routes:
        - id: Product
          uri: http://localhost:8081
          predicates:
            - Path=/product/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PATCH
                - OPTIONS
              allowedHeaders: '*'
              maxAge: 30
        - id: Setting
          uri: http://localhost:8081
          predicates:
            - Path=/settings
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PATCH
                - OPTIONS
              allowedHeaders: '*'
              maxAge: 30
        - id: Category
          uri: http://localhost:8081
          predicates:
            - Path=/categories
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PATCH
                - OPTIONS
              allowedHeaders: '*'
              maxAge: 30
        - id: Orders
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PATCH
                - OPTIONS
              allowedHeaders: '*'
              maxAge: 30
        - id: OrderItems
          uri: http://localhost:8083
          predicates:
            - Path=/orderItems/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PATCH
                - OPTIONS
              allowedHeaders: '*'
              maxAge: 30
        - id: creteOrder
          uri: http://localhost:8083
          predicates:
            - Path=/createOrder
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
                - PATCH
                - OPTIONS
              allowedHeaders: '*'
              maxAge: 30


error.path: /error


server.port: 8080


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      leaseRenewalIntervalInSeconds: 10

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
